name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '19.3.0'

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          ng build --configuration=production --base-href https://kacpermejs.github.io/<github-repo-name>/
          npx ngh --dir=dist/cinema-app-frontend --no-silent --message="Deployed to GitHub Pages"
